services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/laravel
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes: 
    - ./code/laravel:/var/www/laravel
    - ./vm/php/local.ini:/usr/local/etc/php/conf.d/local.ini
         
    networks:
      - laravel_network


  webserver: 
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./vm/nginx/conf.d:/etc/nginx/conf.d/
      - ./code:/var/www
    depends_on:
      - app
    networks:
      - laravel_network
      
  adminer: 
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - laravel_network

  mysql:
      image: mysql:8.0
      container_name: laravel_mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: laravel_db
        MYSQL_USER: laravel_user
        MYSQL_PASSWORD: laravel_password
      ports:
        - "3307:3306"
      volumes:
        - ./db/mysql:/var/lib/mysql
      networks:
        - laravel_network
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s

networks:
  laravel_network:
    driver: bridge  